### ISSUE TITLE
When you add an image from a file, its content type is guessed from the extension, this causes an exception when you copy the worksheet

### ISSUE THREAD

**Issue by zippy1981** [JanKallman/EPPlus#173]
I'll add a test shortly to prove it or probably just a patch. I've contributed in the past on codeplex.

Basically this happens

* Add a non-jpeg image on a worksheet from a file.
* EPPlus "guesses" its a jpeg
* Copy the worksheet
* GDI is told a stream is a jpeg that isn't and EPPLus throws an exception.

**Comment by RonnyRoscher** [comment]
I still get this error in the current EPPlus version 4.5.2.1 / .NET Framework 4.7.2. I tried to add the image with System.Drawing.Image as well as via FileInfo, and I tried different image formats, including .png, .bmp, .jpg and .jpeg. No matter what I do, I get a crash when copying a sheet with the line: excelPackageObject.Workbook.Worksheets.Add(destinationSheetName, sourceSheet);

Below the exception details:
```
ClassName:
System.Runtime.InteropServices.ExternalException

Message:
"General error in GDI+."

StackTrace:
at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
at System.Drawing.Image.Save(Stream stream, ImageFormat format)
at OfficeOpenXml.ExcelWorksheets.CopyDrawing(ExcelWorksheet Copy, ExcelWorksheet workSheet)
at OfficeOpenXml.ExcelWorksheets.Add(String Name, ExcelWorksheet Copy)

ExceptionMethod:
8
Save
System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Drawing.Image
Void Save(System.IO.Stream, System.Drawing.Imaging.ImageCodecInfo, System.Drawing.Imaging.EncoderParameters)
```

**Comment by apocc42** [comment]
PR #251 should fix this issue.
