### ISSUE TITLE
Bug: R1C1 formula parsing breaks if a named range begins with "C" and contains an "R"

### ISSUE THREAD

**Issue by richardtallent** [JanKallman/EPPlus#262]
If a named range's name begins with "C" and contains an "R" anywhere within it, referencing that named range in `.FormulaR1C1` generates the following error:

```
Length cannot be less than zero.
Parameter name: length   at System.String.Substring(Int32 startIndex, Int32 length)
   at OfficeOpenXml.ExcelCellBase.ToAbs_1(String part, Int32 row, Int32 col, Int32 rowIncr, Int32 colIncr)
   at OfficeOpenXml.ExcelCellBase.ToAbs(String part, Int32 row, Int32 col, Int32 rowIncr, Int32 colIncr)
   at OfficeOpenXml.ExcelCellBase.Translate(String value, dlgTransl addressTranslator, Int32 row, Int32 col, Int32 rowIncr, Int32 colIncr)
   at OfficeOpenXml.ExcelCellBase.TranslateFromR1C1(String value, Int32 row, Int32 col)
   at OfficeOpenXml.ExcelRangeBase.set_FormulaR1C1(String value)
```

Minimal test case:
```C#
using(var w = new OfficeOpenXml.ExcelPackage(newFile)) {
	var ws = w.Workbook.Worksheets.Add("Foo");
	ws.Cells[1, 1].FormulaR1C1 = "=CvalidRasdf";
	w.Save();
}
```
Using version 4.5.2.1 on .NET 4.7.2.

I've tested various names, and the patterns of "C*R" or "C*R*" seem to be the only breaking ones I've found.

As always, thanks for the work you put into this library!

**Comment by twebster2** [comment]
I can also replicate the same issue when saving a excel package with a CalculatedColumnFormula.
`
var package = new OfficeOpenXml.ExcelPackage(fs);
var tbl = sheet.Tables.Add(sheet.Cells[1, 1, range.End.Row, range.End.Column], "CheckTable");
tbl.Columns[0].CalculatedColumnFormula =
	"CONCATENATE(CheckTable[[#This Row],[Parent]],CheckTable[[#This Row],[Name]],CheckTable[[#This Row],[Measure]],CheckTable[[#This Row],[MonthEndDate]],CheckTable[[#This Row],[Currency]])";

package.Save();
`

Looks like it is related to this change: https://github.com/JanKallman/EPPlus/commit/97b51ab6a5d68a7afc7aa79af68c4950c1a47c7c#diff-b1669011af1ca17e1cd553ece7672e7e

**Comment by gregamic** [comment]
Same issue using the version 4.5.3.1.
The odd thing is that the CalculatedColumnFormula in my case does not actually requires a "TranslationFromR1C1". But the "needsTranslation" evaluation is wrong because it is case sensitive. 
With the following code :
`bool needsTranslation = r1c1Formula.ToUpper () != Col.CalculatedColumnFormula;`
it seems to be fixed!
