### ISSUE TITLE
Error loading xlsx contains hyper links

### ISSUE THREAD

**Issue by ryanlin1986** [JanKallman/EPPlus#268]
An error occurs when execute the following code:
package.Workbook.Worksheets[1];

Here is  the callstack:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OfficeOpenXml.ExcelWorksheet.LoadHyperLinks(XmlReader xr)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, eWorkSheetHidden hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()

**Comment by sergey-prokhorov** [comment]
hello! did You solve the problem?
