### ISSUE TITLE
Error "Column number out of bounds"

### ISSUE THREAD

**Issue by iSotelo** [JanKallman/EPPlus#291]
I get the following error when I try to add an image to an excel file.

`System.ArgumentException: Column number out of bounds
at OfficeOpenXml.ExcelWorksheet.Column(Int32 col)
at OfficeOpenXml.Drawing.ExcelDrawing.GetColumnWidth(Int32 col)
at OfficeOpenXml.Drawing.ExcelDrawing.SetPixelWidth(Int32 pixels, Single dpi)
at OfficeOpenXml.Drawing.ExcelPicture.SetPosDefaults(Image image)
at OfficeOpenXml.Drawing.ExcelPicture..ctor(ExcelDrawings drawings, XmlNode node, FileInfo imageFile, Uri hyperlink)
at OfficeOpenXml.Drawing.ExcelDrawings.AddPicture(String Name, FileInfo ImageFile, Uri Hyperlink)
at SmartFlowNew.Models.ExcelProcessing.ExportExcelTemplateWithImage(DataTable dataTable, String fileExcel, String title, List`1 listemployeestoexport) in C:\VisualStudio2017Projects\SmartFlow-3\src\WebApps\SmartFlowNew\Models\ExcelProcessing.cs:line 238`

My code is the following:

```
dataTable.Columns["Photo"].DefaultValue = null;
 excelWorksheet.Cells["A5"].LoadFromDataTable(dataTable, true);
excelWorksheet.Cells["A5:AZ"].AutoFitColumns();
ExcelProcessing.SetColumnsName(excelWorksheet);
int rowindex = 5;
int colindex = 12;
int height = 100;
int width = 100;
foreach (KeyValuePair<string, string> item in employeesimages) {
  try{
       if (item.Value != null && item.Value != ""){ 
           FileInfo fi = new FileInfo(item.Value);
           excelWorksheet.Row(rowindex + 1).Height = height;
           ExcelPicture pic = excelWorksheet.Drawings.AddPicture(item.Key, fi);
           pic.SetPosition(rowindex, 1, colindex, 1);
           pic.SetSize(height, width);
           rowindex++;
       }
    }catch (Exception ex){
               Console.WriteLine(ex.ToString());
    }
}
```

I hope you can help me since I have a few days with this problem.

My excel version is 2010

**Comment by MaJaHa95** [comment]
Interestingly, I'm repro'ing this with an Excel sheet I've been provided. Unfortunately I can't share it, and I'm just starting debugging, but I'm able to open and parse the package, but if I immediately, without modification, attempt to save, I receive the same error.

I'll post if I learn more. But it's definitely the case that this can happen without any in-code modifications even being made.

**Comment by MaJaHa95** [comment]
Interestingly, I'm able to get around this particular error by setting `package.DoAdjustDrawings = false`. I'm not sure of the implications of that, but it's a starting point.

**Comment by svm201020** [comment]
Workaround for the bug (EPPlus doesn't check if image resolution exists in: ExcelDrawing.cs, 
internal void SetPixelWidth(int pixels, float dpi), line 400).

If image resolution doesn't set, just set it manually. AddPicture will work fine:

if (img.HorizontalResolution == 0 || img.VerticalResolution == 0)
    img.SetResolution(96, 96);                                       
var excelImage = worksheet.Drawings.AddPicture("img", img);
