### ISSUE TITLE
System.ArgumentException: 'IBM437' is not a supported encoding name - when not targeting .NETFramework

### ISSUE THREAD

**Issue by mark-szabo** [JanKallman/EPPlus#31]
When targeting UWP Fall Creators Update (v10.0.16299) I get this exception when saving excel file from stream.

```
System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at OfficeOpenXml.Packaging.ZipPackage.Save(Stream stream)
   at OfficeOpenXml.ExcelPackage.Save()
   at OfficeOpenXml.ExcelPackage.SaveAs(Stream OutputStream)
   at HtmlScraper.Helpers.<ExcelExportAsync>d__6.MoveNext()
```

The code:
```c#
var stream = await file.OpenAsync(FileAccessMode.ReadWrite);
using (Stream s = stream.GetOutputStreamAt(0).AsStreamForWrite())
{
    excelPackage.SaveAs(s);
}
stream.Dispose();
```

I get this warning at compile but nonetheless it should work.
```
Package 'EPPlus 4.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework 'UAP,Version=v10.0.16299'. This package may not be fully compatible with your project.
```

According to [this](https://github.com/davidfowl/NetStandard/blob/master/NETStandard2.0WithNuGet.md) the same is the problem when using with .NET Standard.

**Comment by VahidN** [comment]
First add a reference to `System.Text.Encoding.CodePages` assembly.
```xml
<ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.3.0" />
</ItemGroup>
```
Then register the missing parts:
```csharp
 Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

**Comment by mark-szabo** [comment]
Thanks @VahidN, this solved the problem! Can we implement this directly into the package?

**Comment by swmal** [comment]
Thanks. Maybe you can do a pull request if this is something that should sit in epplus.
