### ISSUE TITLE
Adding 398 rows gives index out of bound but adding 397 doesn't give a crash .NET Core

### ISSUE THREAD

**Issue by jermeyjungbeker** [JanKallman/EPPlus#310]
```

                package.Save();

                for (int i = 1; i <= 398; i++)
                {
                    wsData.Cells[i, 1].Value = i;
                    wsData.Cells[i, 2].Value = i;
                }
                package.Save();
```
Exception thrown: 'System.IndexOutOfRangeException' in EPPlus.dll
Index was outside the bounds of the array.

```

                for (int i = 1; i <= 397; i++)
                {
                    wsData.Cells[i, 1].Value = i;
                    wsData.Cells[i, 2].Value = i;
                }
                package.Save();
```
Works

Using version 4.5.2.1

**Comment by jermeyjungbeker** [comment]
![error](https://user-images.githubusercontent.com/12142239/45280340-3defeb00-b4d4-11e8-8fe1-9a7150d70902.png)

It crashes here EPPlus\Packaging\DotNetZip\Zlib\Deflate.cs(1463)

**Comment by jermeyjungbeker** [comment]
It seems to be an issue when i run it on windows IOT UWP app specifically. If i run it in a UWP app on my desktop i have no issues. I am gonna try to run it with compression lvl none because that will skip the entire code so it should work. will update on monday.

**Comment by jermeyjungbeker** [comment]
```

 at OfficeOpenXml.Packaging.Ionic.Zlib.DeflateManager.longest_match(Int32 cur_match)
   at OfficeOpenXml.Packaging.Ionic.Zlib.DeflateManager.DeflateSlow(FlushType flush)
   at OfficeOpenXml.Packaging.Ionic.Zlib.DeflateManager.Deflate(FlushType flush)
   at OfficeOpenXml.Packaging.Ionic.Zlib.ZlibCodec.Deflate(FlushType flush)
   at OfficeOpenXml.Packaging.Ionic.Zlib.ZlibBaseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OfficeOpenXml.Packaging.Ionic.Zlib.DeflateStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OfficeOpenXml.Packaging.Ionic.Crc.CrcCalculatorStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OfficeOpenXml.Packaging.Ionic.Zip.ZipOutputStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Flush()
   at OfficeOpenXml.ExcelWorksheet.UpdateRowCellData(StreamWriter sw)
   at OfficeOpenXml.ExcelWorksheet.SaveXml(Stream stream)
   at OfficeOpenXml.ExcelWorksheet.SaveHandler(ZipOutputStream stream, CompressionLevel compressionLevel, String fileName)
   at OfficeOpenXml.Packaging.ZipPackagePart.WriteZip(ZipOutputStream os)
   at OfficeOpenXml.Packaging.ZipPackage.Save(Stream stream)
   at OfficeOpenXml.ExcelPackage.Save()

```

Still getting the error even with compression.None

**Comment by jermeyjungbeker** [comment]
making 100 sheets with 

                for (int i = 1; i <= 397; i++)
                {
                    wsData.Cells[i, 1].Value = i;
                    wsData.Cells[i, 2].Value = i;
                }
                package.Save();
Also works with no problem
