### ISSUE TITLE
NullReferenceException epplus Parallel.For

### ISSUE THREAD

**Issue by hashtriton** [JanKallman/EPPlus#330]
Good afternoon, I just want to apologize for my English. I am writing a program (using the epplus library), which takes an excel file and looks for matches. When it finds replaces some cells. Everything works fine, but for a long time. I decided to implement Parallel.For, however I get an error NullReferenceException on the condition

```
ExcelPackage package_map = new ExcelPackage();
ExcelWorksheet worksheet_map;

ExcelPackage package_rep = new ExcelPackage();
ExcelWorksheet worksheet_rep;

ileInfo mapFile = new FileInfo(Application.StartupPath + "\\Resources\\" + comboBox1.Text+"_ma.xlsx"); package_map = new ExcelPackage(mapFile); 
worksheet_map = package_map.Workbook.Worksheets[1];

package_rep = new ExcelPackage(repFile);
worksheet_rep = package_rep.Workbook.Worksheets[1];
for (int j = 2; j < worksheet_map.Dimension.Rows + 1; j++)
    Parallel.For(2, worksheet_rep.Dimension.Rows + 1, i =>       //ERROR
    {
        if (worksheet_rep.Cells[i, 6].Text == worksheet_map.Cells[j, 1].Text)    
        {
            worksheet_rep.Cells[i, 6].Value = worksheet_map.Cells[j, 4].Text;    
            worksheet_rep.Cells[i, 5].Value = worksheet_map.Cells[j, 3].Text;   
            worksheet_rep.Cells[i, 4].Value = worksheet_map.Cells[j, 2].Text;    
            kol_sov++;
        }
    });
```

**Comment by swmal** [comment]
Your english is excellent, sorry for the late reply. We have not tried to use Parallel.For with EPPlus and I guess it has something to do with thread safety. Will keep this with an enhancement tag.

**Comment by mustantriveni** [comment]
I have implemented parallel foreach and after 2 months I am having issues sometimes
is there any solution there?
Full text of the error message is System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'OfficeOpenXml.ExcelColumn'.
  at OfficeOpenXml.ExcelStyles.<>c__DisplayClass16_1.<SetStyleAddress>b__0(List`1 list, Int32 index, Int32 row, Int32 column, Object args)
  at CellStore`1.SetRangeValueSpecial(Int32 fromRow, Int32 fromColumn, Int32 toRow, Int32 toColumn, SetRangeValueDelegate Updater, Object Value)
  at OfficeOpenXml.ExcelStyles.SetStyleAddress(StyleBase sender, StyleChangeEventArgs e, ExcelAddressBase address, ExcelWorksheet ws, Dictionary`2& styleCashe)
  at OfficeOpenXml.ExcelStyles.PropertyChange(StyleBase sender, StyleChangeEventArgs e)
