### ISSUE TITLE
add picture error in .net core2.1 at Linux

### ISSUE THREAD

**Issue by lumin2** [JanKallman/EPPlus#331]
when run at Linux using .net core2.1 add picture error
 Parameter is not valid.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at OfficeOpenXml.Compatibility.ImageCompat.GetImageAsByteArray(Image image)
   at OfficeOpenXml.Drawing.ExcelPicture..ctor(ExcelDrawings drawings, XmlNode node)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawing(ExcelDrawings drawings, XmlNode node)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()
   at OfficeOpenXml.ExcelWorksheets.Add(String Name, ExcelWorksheet Copy)

**Comment by swmal** [comment]
We will update the System.Drawing package by Microsoft to the latest version in the next version of EPPlus. Hopefully that will resolve your problem.
