### ISSUE TITLE
Saveas 	"The cachesource is not a worksheet"	when includes pivot tables

### ISSUE THREAD

**Issue by henrikjuel** [JanKallman/EPPlus#362]
Note: Please don't file an issue to ask a support related question. We are a small team and can't handle all questions. Questions are referred to https://stackoverflow.com/questions/tagged/epplus
If you have a bug, request of a new feature, make sure you follow these guidelines
[] Write a detailed description of your issue.
[] Attach a test to reproduce your issue, if it is a bug or unexpected behaviour. This is very important. 
[] If your issue requires a template xlsx file to be reproduced, make sure that you attach it to the issue.

**Comment by henrikjuel** [comment]
Using the latest version 4.5.2.1
Simple use of the method :  

excelPackage.SaveAs(saveFile); throws the exception.

Works fine when no pivottables are on the template xlsm file. I can enclose the fully code if needed. I have ensured that all dataconnections in the xlsm file has been removed. i have enclosed the xlsm file
[afdregnskab.zip](https://github.com/JanKallman/EPPlus/files/2644161/afdregnskab.zip)



 stacktrace
at OfficeOpenXml.Table.PivotTable.ExcelPivotCacheDefinition.get_SourceRange()
   at OfficeOpenXml.ExcelWorksheet.SavePivotTables()
   at OfficeOpenXml.ExcelWorksheet.Save()
   at OfficeOpenXml.ExcelWorkbook.Save()
   at OfficeOpenXml.ExcelPackage.Save()
