### ISSUE TITLE
Out of memory exception when loading large Excel file

### ISSUE THREAD

**Issue by ChristanMadsen** [JanKallman/EPPlus#404]
I am trying to load a large Excel file and I get an Out of memory exception. The file is 250 MB and contains 950392 rows and 64 columns - well under the specified max. I have plenty of memory on the machine.

The excpetion happens in the call to the ExcelPackage conttructor:

            FileInfo output = new FileInfo(filepath);

            using (var package = new ExcelPackage(output))

Stacktrace:
   at OfficeOpenXml.Packaging.ZipPackage..ctor(Stream stream)
   at OfficeOpenXml.ExcelPackage.ConstructNewFile(String password)
   at OfficeOpenXml.ExcelPackage..ctor(FileInfo newFile)

I actually need to process files up to 4 times larger than this one - is there a way to do that?

**Comment by ericleigh007** [comment]
Perhaps Jan would consider making a special version of this package, or just publishing the "regular" AnyCPU version as well as an x64 version?
Failing that, I've seen some fork this library and build the library themselves for x64, and get around size limits.  Be aware, however, the saving of all that data will take a good deal of time.  This is where one might abandon the simplicity of Excel and use real database tools.
