### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by rayzorben** [JanKallman/EPPlus#416]
I am getting the following error when trying to check for the existence of a worksheet. This is a file that was previously saved with EPPlus

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OfficeOpenXml.ExcelRangeBase..ctor(ExcelWorksheet xlWorksheet, String address)
   at OfficeOpenXml.ExcelNamedRangeCollection.Add(String Name, ExcelRangeBase Range)
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()
   at DataMigration.Program.Process(ProgramOptions program, MigrationOptions commandLine) in C:\Users\ray\source\repos\DataMigration\DataMigration\Program.cs:line 93
```

This is Program.cs:93
`                if (package != null && package.Workbook != null && package.Workbook.Worksheets != null && package.Workbook.Worksheets.Exists("Overview"))`

Note, I set a breakpoint on the first line in .Exists and it never gets hit, so it never gets there, however here is the (modified) code

```
        public static bool Exists(this ExcelWorksheets worksheets, string name)
        {
            foreach (var worksheet in worksheets)
            {
                if (worksheet != null & worksheet.Name == name)
                {
                    return true;
                }
            }
            return false;
            //return worksheets.FirstOrDefault(x => x.Name == name) != null;           
        }       
```

In Visual Studio, I checked that none of the values are null

![image](https://user-images.githubusercontent.com/7737834/53542388-dd855200-3ae3-11e9-9fc4-6c3ac4ef19ed.png)

**Comment by rayzorben** [comment]
This seems to happen if there are Names in the workbook that refer to a sheet/table/range that no longer exists.
