### ISSUE TITLE
AutoFitColumns on long data

### ISSUE THREAD

**Issue by Errors4l** [JanKallman/EPPlus#445]
**Write a detailed description of your issue.**
When trying to call AutoFitColumns on a range that includes data exceeding ~32000 characters, Graphics.MeasureStrings throws a generic GDI+ exception. This applies even when supplying the method with a max length.

```
System.Runtime.InteropServices.ExternalException
  HResult=0x80004005
  Message=A generic error occurred in GDI+.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)
```
https://github.com/JanKallman/EPPlus/blob/30cdb0dfa125b5a780dff21ebf4fc0b7fa5defdd/EPPlus/ExcelRangeBase.cs#L909

**Attach a test to reproduce your issue, if it is a bug or unexpected behaviour. This is very important.**
Apologies for incomplete code. I can't share the code I'm working with. This seems to be all that's necessary to reproduce the bug.
```
ws.Cells[1, 1].Value = new string('a', 50000);
ws.Cells[1, 1].AutoFitColumns();
```

**Related**
- Issue on StackOverflow - https://stackoverflow.com/questions/44687723/autofit-long-strings-with-epplus
- MeasureString error on Stackoverflow - https://stackoverflow.com/questions/30556042/a-generic-error-occurred-in-gdi-while-using-measurestring

**Comment by JanKallman** [comment]
Thanks, added a fix that truncates the string to 32000 chars before using it as a parameter to MeasureString.

**Comment by justin-oj-orange** [comment]
@JanKallman Has this fully made it into the repo yet, we are using v4.5.3.1. If not (not implying anything) is there an easy work around, apart from truncating every cell value we supply of course
