### ISSUE TITLE
Bug when Trying to upload an excel File

### ISSUE THREAD

**Issue by riteshbxr** [JanKallman/EPPlus#48]
I have an Excel file which I tried to load and Following error Occured related to the EPPlus while trying to access the package Worksheet immediately after load.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OfficeOpenXml.ExcelNamedRangeCollection.AddName(String Name, ExcelNamedRange item)
   at OfficeOpenXml.ExcelNamedRangeCollection.Add(String Name, ExcelRangeBase Range)
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()

the file that was being loaded in the Excepackage via Stream (public ExcelPackage(Stream newStream);) and I instantly tried to access the Worksheet. When I debugged it with F10 (Visual Studio), It didn't trigger the error. So The Loading might be taking some time and locad data might be returning before it completely loads or something like that.

[Sample Error File.xlsx](https://github.com/JanKallman/EPPlus/files/1449760/Sample.Error.File.xlsx)
File being loaded contains sensitive data so could not share it... When I tried to Edit the sheet... the error could not be reproduced with new sheet. I am Attaching the sheet with changed data (could not reproduce error with it, I can't send original sheet as its data is not my property).

If you could not detect the issue.. Let me know.. I will try harder to generate a sample error excel file for this...

Note: Please don't file an issue to ask a support related question. We are a small team and can't handle all questions. Questions are referred to https://stackoverflow.com/questions/tagged/epplus
If you have a bug, request of a new feature, make sure you follow these guidelines
[] Write a detailed description of your issue.
[] Attach a test to reproduce your issue, if it is a bug or unexpected behaviour. This is very important. 
[] If your issue requires a template xlsx file to be reproduced, make sure that you attach it to the issue.

**Comment by IVANS0N** [comment]
I got the same error and found the reason in ExcelWorkbook.cs.
In method `ExcelWorkbook.GetDefinedNames` defined  
 `XmlNodeList nl = WorkbookXml.SelectNodes("//d:definedNames/d:definedName", NameSpaceManager);`

Then, in `foreach (XmlElement elem in nl)` we got 2 elements with same name `/d:definedName` because double slash in first element probably escaped.

And finally, at 255 or 259 rows, we have exception from the topic, with duplicate element name  `namedRange = Worksheets[localSheetID + _package._worksheetAdd].Names.Add(elem.GetAttribute("name"), new ExcelRangeBase(this, Worksheets[addr._ws], fullAddress, false));`

My sample file 
[Template error - changed.xlsx](https://github.com/JanKallman/EPPlus/files/4044626/Template.error.-.changed.xlsx)
