### ISSUE TITLE
The type initializer for 'Gdip' threw an exception.Unable to load shared library 'libgdiplus' or one of its dependencies

### ISSUE THREAD

**Issue by ChiakiYu** [JanKallman/EPPlus#614]
CentOS Linux release 7.7.1908 (Core)
docker:19.03.5
Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

WORKDIR /app
EXPOSE 80
COPY . .

ENTRYPOINT ["dotnet", "Project.dll"]
```
Error Log:
```
The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()
   at OfficeOpenXml.ExcelColumn.AutoFit()
```

**Comment by ChiakiYu** [comment]
this Dockerfile is work:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

RUN apt-get update && apt-get install -y libgdiplus

WORKDIR /app
EXPOSE 80
COPY . .

ENTRYPOINT ["dotnet", "Project.dll"]
```
