### ISSUE TITLE
.LoadFromCollection(...) does not work with IEnumerable<dynamic>

### ISSUE THREAD

**Issue by TerryDieckmann** [JanKallman/EPPlus#8]
Whenever I use .LoadFromCollection(...) with a dynamic type, the exception “Index was outside the bounds of the array” is thrown. Is there any fix for this, yet?

**Comment by JanKallman** [comment]
Please provide some code to replicate

**Comment by TerryDieckmann** [comment]
I've uploaded the class that I'm using here:
<script src="https://gist.github.com/TerryDieckmann/12febeecadb26797925b3f8680c00356.js"></script>

**Comment by TerryDieckmann** [comment]
I got it working with the following code by just creating a datatable and looping over the properties.
```
public static byte[] Save(IEnumerable<dynamic> list)
{
    var stream = new MemoryStream();

    using (var package = new ExcelPackage())
    {
        var excelWorksheet = package.Workbook.Worksheets.Add(_defaultWorksheet);
        var isNew = excelWorksheet.Dimension == null;

        var dataTable = new DataTable(_defaultTableName);
        var collection = list as IList<dynamic> ?? list.ToList();

        var properties = ((IDictionary<string, object>)collection.First())
            .ToDictionary(x => x.Key, x => x.Value);

        foreach (var property in properties)
            dataTable.Columns.Add(property.Key);

        foreach (var item in collection.ToList())
        {
            var dataRow = dataTable.NewRow();

            var o = (IDictionary<string, object>) item;

            foreach (var p in properties)
                dataRow[p.Key] = o[p.Key];

            dataTable.Rows.Add(dataRow);
        }

        if (isNew)
            excelWorksheet.Cells[1, 1].LoadFromDataTable(dataTable, true);
        else
            excelWorksheet.Cells[excelWorksheet.Dimension.End.Row + 1, 1].LoadFromDataTable(dataTable, true);

        if (excelWorksheet.Dimension != null)
            excelWorksheet.InsertRow(excelWorksheet.Dimension.End.Row + 2, 5);

        package.SaveAs(stream);
    }

    return stream.ToArray();
}
```
It would be great if this is implemented out of the box :)

**Comment by bborad** [comment]
Hi

I am having same issue with List<Object>.

is there a solution for this for have to create table to export?

Thanks

**Comment by bborad** [comment]
Code

       
```csharp
             IEnumerable<object> collection
              var worksheet = package.Workbook.Worksheets.Add("Sheet1");
                worksheet.Cells["A1"].LoadFromCollection(collection, true);
                byte[] bytes = package.GetAsByteArray();
                return bytes;
 
```
StackTrace

```csharp
   at OfficeOpenXml.ExcelRangeBase.LoadFromCollection[T](IEnumerable`1 Collection, Boolean PrintHeaders, TableStyles TableStyle, BindingFlags memberFlags, MemberInfo[] Members)
   at OfficeOpenXml.ExcelRangeBase.LoadFromCollection[T](IEnumerable`1 Collection, Boolean PrintHeaders)

```

**Comment by tommy025** [comment]
I got the same problem. In my code this method works for IEnumerable<string>, but throws IndexOutOfRangeException for IEnumerable<double>.

**Comment by crossan007** [comment]
I'm having (what I think is) the same issue.

I'm obtaining an object collection from *somewhere*, and passing that through a `select` LINQ statement.  The select clause is generating new "dynamic objects" since I do not want all properties of the source object present on my spreadsheet.

For reference the offending code block is as follows:
```
var p = entities.Select<MetaEntity,Object>((me,o) => { return new { a = 1 };  }).ToList<Object>();
worksheet.Cells.LoadFromCollection(p,true);
```

entities here contains two members, each of which is resulting in a new object which (for testing only) has a single property ("a") with a value of "1".

![image](https://user-images.githubusercontent.com/11679900/42241804-d41b6036-7ed9-11e8-8088-fd16efde96b2.png)

and this fails with a "Column out of Range" Exception:
![image](https://user-images.githubusercontent.com/11679900/42241833-f0c22620-7ed9-11e8-919a-88ee0f8612fd.png)

**Comment by crossan007** [comment]
Disregard that previous comment.   Turns out my LINQ was not quite right.  

This fixed it for me:
```
var p = entities.Select((me,o) => { return new { a = 1 };  });
worksheet.Cells.LoadFromCollection(p,true);
```

**Comment by alexlya** [comment]
Can confirm the issue is present.  Here is MVP:

    using System.Collections.Generic;
    using OfficeOpenXml;

    namespace Tests.One
    {
        class Program
        {
            static void Main(string[] args)
            {
                using (var package = new ExcelPackage())
                {
                    var worksheet = package.Workbook.Worksheets.Add("Sheet 1");

                    var persons = new List<Person>();
                    persons.Add(new Person() { Name = "a" });

                    worksheet.Cells["A1"].LoadFromCollection(persons); // "Column out of range" here 
                }
            }

            public class Person
            {
                public string Name;
            }
        }
    }

Stack trace:

    at OfficeOpenXml.ExcelRange.ValidateRowCol(Int32 Row, Int32 Col)
    at OfficeOpenXml.ExcelRange.get_Item(Int32 FromRow, Int32 FromCol, Int32 ToRow, Int32 ToCol)
    at OfficeOpenXml.ExcelRangeBase.LoadFromCollection[T](IEnumerable`1 Collection, Boolean PrintHeaders, TableStyles TableStyle, BindingFlags memberFlags, MemberInfo[] Members)
    at OfficeOpenXml.ExcelRangeBase.LoadFromCollection[T](IEnumerable`1 Collection)

**Comment by alexlya** [comment]
Just discovered that `LoadFromCollection` with custom object works fine in MVC. MCVE of contents of controller in MVC app:

    using OfficeOpenXml;
    using System.Collections.Generic;
    using System.Web.Mvc;

    namespace Two.Controllers
    {
        public class HomeController : Controller
        {
            public ActionResult Index()
            {
                ExcelPackage pck = new ExcelPackage();
                ExcelWorksheet ew = pck.Workbook.Worksheets.Add("Sheet 1");

                List<Person> list = new List<Person>();
                list.Add(new Person() { Name = "a" });
                list.Add(new Person() { Name = "b" });

                ew.Cells["A1"].LoadFromCollection(list, true);
                ew.Cells["A:AZ"].AutoFitColumns();

                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment: filename=" + "abc" + ".xlsx");
                Response.BinaryWrite(pck.GetAsByteArray());
                Response.End();
                return View();
            }

            class Person
            {
                public string Name { get; set; }
            }
        }
    }

**Comment by brmiguel5** [comment]
@alexlya @TerryDieckmann 
I also ran into the 'Column out of range' exception when calling a simple extension that uses LoadFromCollection. I made some tests and I think I found my issue..

![image](https://user-images.githubusercontent.com/43035155/55344463-aa046180-54ad-11e9-9ee7-06c0fc19e07d.png)

After some thought I realized my class had **only fields, no properties**... so I turned them into properties and...

![image](https://user-images.githubusercontent.com/43035155/55344535-e1730e00-54ad-11e9-9735-faa4501cdd11.png)

It works! My guess guess is as good as yours... namely, LoadFromCollection is only reading properties and not fields. I'm not sure this is a bug though. Do we really want LoadFromCollection to include fields? 

Anyways, hope this helps.

**Comment by mferri17** [comment]
Same problem here using `object` to extract a method. It seems that `LoadFromCollection()` only works with custom classes or anonymous types.

**Comment by TheOutsider89** [comment]
@mferri17 What was the workaround that you had to make to get it done?

**Comment by mferri17** [comment]
@TheOutsider89 I simply gave up on that :(

**Comment by jpchand67** [comment]
I was getting the same error and got it working by passing in a DataTable and then calling LoadFromDataTable instead: 
 worksheet.Cells["A1"].LoadFromDataTable(dtData,true);

**Comment by jumppard** [comment]
> @alexlya @TerryDieckmann
> I also ran into the 'Column out of range' exception when calling a simple extension that uses LoadFromCollection. I made some tests and I think I found my issue..
> 
> ![image](https://user-images.githubusercontent.com/43035155/55344463-aa046180-54ad-11e9-9ee7-06c0fc19e07d.png)
> 
> After some thought I realized my class had **only fields, no properties**... so I turned them into properties and...
> 
> ![image](https://user-images.githubusercontent.com/43035155/55344535-e1730e00-54ad-11e9-9735-faa4501cdd11.png)
> 
> It works! My guess guess is as good as yours... namely, LoadFromCollection is only reading properties and not fields. I'm not sure this is a bug though. Do we really want LoadFromCollection to include fields?
> 
> Anyways, hope this helps.

This solved my problem. Many thanks to @brmiguel5 :)
